# Generated by Django 6.0 on 2026-01-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_document_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='apk_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='figma_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
